GET http://localhost:8081/api

###

POST http://localhost:8081/login
Content-Type: application/x-www-form-urlencoded

username=admin
&password=admin

###

GET http://localhost:8081/logout

###

POST http://localhost:8081/api/buyers
Content-Type: application/json

{
  "email": "u1@gmail.com",
  "password": "pass1",
  "cpf": "111.222.333-44"
}

###

POST http://localhost:8081/api/sellers
Content-Type: application/json

{
  "email": "u2@gmail.com",
  "password": "pass2",
  "cnpj": "11.222.333/0001-44"
}

###

GET http://localhost:8081/api/buyers

###

GET http://localhost:8081/api/sellers

###

GET http://localhost:8081/api/users

###

GET http://localhost:8081/api/users/1

###

# expected to receive 405 HTTP error response
POST http://localhost:8081/api/users
Content-Type: application/json

{
  "email": "u2@gmail.com",
  "password": "pass2"
}

###

GET http://localhost:8081/api/listings

###

GET http://localhost:8081/api/listings/1

###

POST http://localhost:8081/api/listings
Content-Type: application/json

{
  "name": "Listing 1",
  "price": 3.14,
  "quantity": 10,
  "seller": "http://localhost:8081/api/seller/2"
}

###

GET http://localhost:8081/api/listings/1/seller

###

GET http://localhost:8081/api/sellers/2/listings

###

POST http://localhost:8081/api/listings
Content-Type: application/json

{
  "name": "Listing 2",
  "price": 4.99,
  "quantity": 5
}

###

PUT http://localhost:8081/api/listings/2/seller
Content-Type:text/uri-list

http://localhost:8081/api/seller/2

###

# inverse (insertion in listings) doesn't work (insertion in seller does)

# POST http://localhost:8081/api/sellers/2/listings
# Content-Type:text/uri-list

# http://localhost:8081/api/listings/2

###

GET http://localhost:8081/api/purchases

###

GET http://localhost:8081/api/purchases/1

###

POST http://localhost:8081/api/purchases
Content-Type: application/json

{
  "total": 3.14,
  "date": "2023-11-15",
  "buyer": "http://localhost:8081/api/buyers/1"
}

###

GET http://localhost:8081/api/purchases/1/buyer

###

GET http://localhost:8081/api/buyers/1/purchases

###

GET http://localhost:8081/api/categories

###

POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "name": "Category 1"
}

###

POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "name": "Category 2",
  "parent": "http://localhost:8081/api/categories/1"
}

###

POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "name": "Category 2b",
  "parent": "http://localhost:8081/api/categories/1"
}

###

POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "name": "Category 3",
  "parent": "http://localhost:8081/api/categories/2"
}

###

GET http://localhost:8081/api/categories/1/subcategories

###

GET http://localhost:8081/api/categories/3/parent

###

GET http://localhost:8081/api/tags

###

POST http://localhost:8081/api/tags
Content-Type: application/json

{
  "name": "Tag 1"
}

###

POST http://localhost:8081/api/tags
Content-Type: application/json

{
  "name": "Tag 2"
}

###

POST http://localhost:8081/api/tags
Content-Type: application/json

{
  "name": "Tag 3"
}

###

PUT http://localhost:8081/api/listings/1/tags
Content-Type:text/uri-list

http://localhost:8081/api/tags/1
http://localhost:8081/api/tags/3

###

GET http://localhost:8081/api/listings/1/tags

###

GET http://localhost:8081/api/tags/1/listings

###

# insertion on inverse (add listing to tag instead of adding tag to listing) won't work
# PUT http://localhost:8081/api/tags/2/listings
# Content-Type:text/uri-list

# http://localhost:8081/api/listings/1
